import Link from "next/link";
import { HeroPreview } from "@/components/hero-preview";

export default function LandingPage() {
  return <main className="landing-page">
    <header className="landing-nav"><Link className="brand" href="/"><span className="brand-mark">r<span>.</span></span><span>rolegrove</span></Link><nav><Link href="#features">Features</Link><Link href="#how-it-works">How it works</Link></nav><div className="landing-nav-actions"><Link className="login-link" href="/login">Log in</Link><Link className="primary-button" data-umami-event="start-workspace" href="/register">Get started <span>↗</span></Link></div></header>
    <section className="hero-section"><div className="hero-content"><div className="eyebrow"><span className="live-dot"/> A CALMER JOB SEARCH STARTS HERE</div><h1>Your next chapter<br/>deserves <em>a little order.</em></h1><p className="hero-subtitle">Keep every application, interview, and follow-up in one thoughtful space. Spend less time keeping track and more time finding the right fit.</p><div className="hero-actions"><Link className="primary-button hero-cta" data-umami-event="start-workspace" href="/register">Start your free workspace <span>→</span></Link><Link className="secondary-button" href="#how-it-works">See how it works <span>↓</span></Link></div><div className="hero-proof"><div className="avatar-stack"><i>J</i><i>M</i><i>A</i><i>+</i></div><span>Your search, growing one step at a time.</span></div></div><HeroPreview/></section>
    <div className="trust-strip"><span>MADE FOR THE WHOLE JOURNEY</span><i/> Capture the application <i/> Prepare for the interview <i/> Celebrate the next step</div>
    <section className="features-section" id="features"><div className="section-kicker">A LITTLE MORE CLARITY</div><h2>Everything you need to<br/>keep moving forward.</h2><p className="section-intro">A job search has a lot of little moving parts. Rolegrove gives them a place to land.</p><div className="feature-grid"><article className="feature-card feature-wide"><div className="feature-icon lavender">▦</div><h3>See the whole picture</h3><p>Know what you’ve sent, where conversations stand, and what deserves a follow-up — without opening twelve tabs.</p><div className="feature-mini-stats"><span><small>APPLIED</small><b>12</b></span><i/><span><small>INTERVIEWS</small><b>4</b></span><i/><span><small>OFFERS</small><b>1</b></span></div></article><article className="feature-card"><div className="feature-icon peach">◷</div><h3>Catch the next step</h3><p>Save interview dates and follow-ups where you’ll actually see them. A gentle nudge, right on time.</p><div className="feature-date"><i>OCT<br/><b>02</b></i><span><b>Portfolio review</b><small>Linear · 10:30 AM</small></span><span className="feature-date-dot"/></div></article><article className="feature-card"><div className="feature-icon mint">↗</div><h3>Keep your data yours</h3><p>Your workspace belongs to you. Export your applications to CSV whenever you need a copy.</p><div className="export-preview"><span>applications-september.csv</span><b>↓</b></div></article></div></section>
    <section className="steps-section" id="how-it-works"><div><div className="section-kicker">SIMPLE BY DESIGN</div><h2>Get back to the<br/>part that matters.</h2><p>A small place for the work you’re already doing.</p><Link className="primary-button" href="/register">Create your workspace <span>→</span></Link></div><div className="steps-list"><article><span>01</span><div><h3>Save an opportunity</h3><p>Add a role in seconds. Keep the company, position, link, and details together.</p></div></article><article><span>02</span><div><h3>Move it along</h3><p>Update the status as things progress. Your dashboard stays current automatically.</p></div></article><article><span>03</span><div><h3>Know what’s next</h3><p>Add the next interview or follow-up and make the next small step visible.</p></div></article></div></section>
    <section className="final-cta"><div className="final-ornament">✳</div><div className="section-kicker">ONE GOOD STEP AT A TIME</div><h2>Make room for your next chapter.</h2><p>Start a free personal workspace and give your job search a little breathing room.</p><Link className="primary-button hero-cta" href="/register">Get started for free <span>→</span></Link><small>No credit card. No pressure. Just a clearer view.</small></section>
    <footer className="landing-footer"><Link className="brand" href="/"><span className="brand-mark">r<span>.</span></span><span>rolegrove</span></Link><span>Made for the next chapter <i>♥</i></span><div><Link href="/login">Log in</Link><Link href="/register">Create account</Link></div></footer>
  </main>;
}
