"use client";
import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { User } from "@/lib/auth";
import type { Application, ApplicationStatus } from "@/lib/applications";

type View = "Applications" | "Calendar" | "Insights" | "Settings";
type Confirmation = { kind: "delete"; application: Application } | { kind: "logout" };
const filters = ["All applications", "Applied", "Interview", "Offer", "Rejected", "Withdrawn"] as const;
const statusTone: Record<ApplicationStatus, string> = { Applied: "applied", Interview: "interview", Offer: "offer", Rejected: "rejected", Withdrawn: "withdrawn" };
const icons: Record<string, string> = { Applications: "▦", Calendar: "▢", Insights: "⌁", Settings: "⚙" };
const colorFor = (name: string) => ["violet", "blue", "green", "coral"][Array.from(name).reduce((n, ch) => n + ch.charCodeAt(0), 0) % 4];
const shortDate = (value: string) => value ? new Date(`${value}T12:00:00`).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }) : "—";
const emptyForm = (): Partial<Application> => ({ company: "", role: "", status: "Applied", applied_on: new Date().toISOString().slice(0,10), location: "", salary: "", job_url: "", notes: "", follow_up_date: "", follow_up_note: "" });

export function Dashboard({ initialUser, initialApplications }: { initialUser: User; initialApplications: Application[] }) {
  const router = useRouter();
  const [user, setUser] = useState(initialUser);
  const [applications, setApplications] = useState(initialApplications);
  const [view, setView] = useState<View>("Applications");
  const [filter, setFilter] = useState<string>("All applications");
  const [query, setQuery] = useState("");
  const [editing, setEditing] = useState<Application | null>(null);
  const [modal, setModal] = useState(false);
  const [toast, setToast] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [confirmation, setConfirmation] = useState<Confirmation | null>(null);

  const counts = useMemo(() => ({ total: applications.length, interviews: applications.filter(a => a.status === "Interview").length, offers: applications.filter(a => a.status === "Offer").length, applied: applications.filter(a => a.status === "Applied").length }), [applications]);
  const visible = useMemo(() => applications.filter(a => (filter === "All applications" || a.status === filter) && `${a.company} ${a.role} ${a.location} ${a.notes}`.toLowerCase().includes(query.toLowerCase())), [applications, filter, query]);
  const upcoming = useMemo(() => applications.filter(a => a.follow_up_date && a.follow_up_date >= new Date().toISOString().slice(0,10)).sort((a,b) => a.follow_up_date.localeCompare(b.follow_up_date)), [applications]);
  function announce(message: string) { setToast(message); window.setTimeout(() => setToast(""), 2800); }
  function openNew() { setEditing(null); setError(""); setModal(true); }
  async function saveApplication(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError("");
    const data = new FormData(event.currentTarget);
    const payload = Object.fromEntries(data.entries());
    try {
      const response = await fetch(editing ? `/api/applications/${editing.id}` : "/api/applications", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
      const result = await response.json();
      if (!response.ok) { setError(result.error || "Could not save this application."); return; }
      setApplications(current => editing ? current.map(a => a.id === editing.id ? result.application : a) : [result.application, ...current]);
      setModal(false); announce(editing ? "Application updated" : "Application added");
    } catch { setError("We couldn’t reach the server. Try again."); }
    finally { setBusy(false); }
  }
  async function changeStatus(application: Application, status: ApplicationStatus) {
    const response = await fetch(`/api/applications/${application.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...application, status }) });
    const result = await response.json();
    if (!response.ok) { announce(result.error || "Could not update status"); return; }
    setApplications(current => current.map(a => a.id === application.id ? result.application : a));
    announce(`${application.company} moved to ${status}`);
  }
  async function deleteApplication(application: Application) {
    setConfirmation({ kind: "delete", application });
  }
  async function confirmDelete(application: Application) {
    setConfirmation(null);
    const response = await fetch(`/api/applications/${application.id}`, { method: "DELETE" });
    const result = await response.json();
    if (!response.ok) { announce(result.error || "Could not delete application"); return; }
    setApplications(current => current.filter(a => a.id !== application.id)); announce("Application deleted");
  }
  function exportCsv() {
    const header = ["Company","Role","Status","Applied on","Location","Salary","Job URL","Follow-up date","Follow-up note","Notes"];
    const rows = applications.map(a => [a.company,a.role,a.status,a.applied_on,a.location,a.salary,a.job_url,a.follow_up_date,a.follow_up_note,a.notes]);
    const csv = [header,...rows].map(row => row.map(value => `"${String(value ?? "").replaceAll('"','""')}"`).join(",")).join("\r\n");
    const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "rolegrove-applications.csv"; anchor.click(); URL.revokeObjectURL(url); announce("Your CSV export is ready");
  }
  function logout() { setConfirmation({ kind: "logout" }); }
  async function confirmLogout() { setConfirmation(null); await fetch("/api/auth/logout", { method: "POST" }); router.push("/"); router.refresh(); }

  return <main className="shell"><aside className="sidebar"><a className="brand" href="/dashboard"><span className="brand-mark">r<span>.</span></span><span>rolegrove</span></a><div className="workspace"><div className="workspace-avatar">{user.name.slice(0,1).toUpperCase()}</div><div><strong>{user.name.split(" ")[0]}’s workspace</strong><small>Personal plan</small></div><span className="workspace-chevron">⌄</span></div><p className="nav-label">WORKSPACE</p><nav className="nav">{(["Applications","Calendar","Insights"] as View[]).map(item=><button key={item} className={view===item?"nav-item active":"nav-item"} onClick={()=>setView(item)}><span className="nav-symbol">{icons[item]}</span><span>{item === "Calendar" ? "Follow-ups" : item}</span>{item==="Applications"&&<span className="nav-count">{counts.total}</span>}{item==="Calendar"&&upcoming.length>0&&<span className="nav-count">{upcoming.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="tip-card"><div className="tip-spark">✳</div><strong>A little progress adds up.</strong><p>Keep your momentum. You’re doing better than you think.</p><div className="tip-progress"><span style={{width:`${Math.min(100,counts.total*10)}%`}}/></div><small>{counts.total} application{counts.total===1?"":"s"} tracked</small></div><button className={view==="Settings"?"nav-item active":"nav-item"} onClick={()=>setView("Settings")}><span className="nav-symbol">{icons.Settings}</span><span>Settings</span></button><div className="profile"><div className="profile-avatar">{user.name.split(/\s+/).map(v=>v[0]).slice(0,2).join("").toUpperCase()}</div><div><strong>{user.name}</strong><small>{user.email}</small></div><button className="profile-more" aria-label="Log out" title="Log out" onClick={logout}>↪</button></div></div></aside>
    <section className="main-area"><header className="topbar"><div className="breadcrumbs">Workspace <span>/</span> <strong>{view}</strong></div><div className="top-actions"><span className="today-label">{new Date().toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric"})}</span><div className="top-avatar">{user.name.split(/\s+/).map(v=>v[0]).slice(0,2).join("").toUpperCase()}</div></div></header><div className="content">
      {view === "Applications" && <><div className="welcome-row"><div><div className="eyebrow"><span className="live-dot"/> YOUR JOB SEARCH, IN GOOD ORDER</div><h1>Good {new Date().getHours()<12?"morning":new Date().getHours()<18?"afternoon":"evening"}, {user.name.split(" ")[0]} <span>✳</span></h1><p className="subtitle">One step at a time. Here’s where things stand.</p></div><button className="primary-button" onClick={openNew}>＋ Add application</button></div>
        <div className="stats-grid"><Stat title="Applications sent" value={counts.total} hint={`${counts.applied} active`} tone="lavender"/><Stat title="In conversation" value={counts.interviews} hint="active interviews" tone="peach"/><Stat title="Offers received" value={counts.offers} hint="you’ve got this" tone="mint"/></div>
        {upcoming[0]&&<section className="next-card"><div className="next-icon">✦</div><div className="next-copy"><span className="next-label">UP NEXT <span>·</span> DON’T FORGET</span><strong>{upcoming[0].follow_up_note || `Follow up with ${upcoming[0].company}`}</strong><small>{upcoming[0].company} · {shortDate(upcoming[0].follow_up_date)} <span>·</span> {upcoming[0].role}</small></div><button className="text-button" onClick={()=>{setView("Calendar");}}>View all →</button><div className="next-decoration"/></section>}
        <section className="applications-section"><div className="section-heading"><div><h2>Your applications</h2><p>Every opportunity, organized in one place.</p></div><button className="export-button" onClick={exportCsv}>↓ &nbsp;Export CSV</button></div><div className="table-card"><div className="table-toolbar"><div className="filter-tabs">{filters.map(item=><button key={item} className={filter===item?"filter-tab selected":"filter-tab"} onClick={()=>setFilter(item)}>{item}<span>{item==="All applications"?applications.length:applications.filter(a=>a.status===item).length}</span></button>)}</div><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search applications" aria-label="Search applications"/><kbd>⌘ K</kbd></label></div><div className="table-scroll"><table><thead><tr><th>COMPANY & ROLE</th><th>STATUS</th><th>DATE APPLIED</th><th>LOCATION</th><th>FOLLOW-UP</th><th>ACTIONS</th></tr></thead><tbody>{visible.map(app=><tr key={app.id}><td><div className="company-cell"><span className={`company-logo ${colorFor(app.company)}`}>{app.company.slice(0,1).toUpperCase()}</span><span className="company-text"><strong>{app.company}</strong><small>{app.role}</small></span></div></td><td><label className={`status ${statusTone[app.status]}`}><i/><select aria-label={`Change ${app.company} status`} value={app.status} onChange={e=>changeStatus(app,e.target.value as ApplicationStatus)}>{filters.slice(1).map(s=><option key={s}>{s}</option>)}</select></label></td><td className="date-cell">{shortDate(app.applied_on)}</td><td className="location-cell">{app.location||"—"}</td><td className="location-cell">{app.follow_up_date?shortDate(app.follow_up_date):"—"}</td><td><div className="row-actions"><button onClick={()=>{setEditing(app);setError("");setModal(true);}} aria-label={`Edit ${app.company}`} title="Edit">✎</button><button onClick={()=>deleteApplication(app)} aria-label={`Delete ${app.company}`} title="Delete">×</button></div></td></tr>)}{visible.length===0&&<tr><td className="empty-state" colSpan={6}><span>⌕</span><strong>{applications.length?"No applications found":"Your workspace is ready"}</strong><small>{applications.length?"Try another search or status filter.":"Add your first opportunity to start keeping track."}</small>{applications.length===0&&<button className="primary-button" onClick={openNew}>＋ Add your first application</button>}</td></tr>}</tbody></table></div><div className="table-footer"><span>Showing <strong>{visible.length}</strong> of <strong>{applications.length}</strong> applications</span><span>Your data is saved to your private workspace.</span></div></div></section></>}
      {view === "Calendar" && <><PageHeading eyebrow="KEEP THE NEXT STEP CLOSE" title="Follow-ups" description="Interviews, check-ins, and reminders you’ve added." action={<button className="primary-button" onClick={openNew}>＋ Add application</button>}/><div className="calendar-layout"><div className="calendar-date-card"><span className="section-kicker">TODAY</span><strong>{new Date().toLocaleDateString("en-US",{day:"2-digit"})}</strong><span>{new Date().toLocaleDateString("en-US",{weekday:"long",month:"long",year:"numeric"})}</span><i>✳</i></div><div className="followup-list"><div className="section-heading"><div><h2>Upcoming reminders</h2><p>Sorted by the date you’ll want to take action.</p></div></div>{upcoming.length?upcoming.map(a=><article className="followup-item" key={a.id}><div className="followup-date"><b>{new Date(`${a.follow_up_date}T12:00:00`).toLocaleDateString("en-US",{day:"2-digit"})}</b><span>{new Date(`${a.follow_up_date}T12:00:00`).toLocaleDateString("en-US",{month:"short"})}</span></div><div className="followup-info"><strong>{a.follow_up_note||`Follow up with ${a.company}`}</strong><span>{a.company} · {a.role}</span><small>Application sent {shortDate(a.applied_on)}</small></div><button className="export-button" onClick={()=>{setEditing(a);setError("");setModal(true);}}>Edit reminder</button></article>):<div className="calendar-empty"><span>◷</span><strong>No upcoming reminders yet</strong><p>Add an interview or follow-up date to an application and it’ll show up here.</p><button className="primary-button" onClick={openNew}>＋ Add an application</button></div>}</div></div></>}
      {view === "Insights" && <><PageHeading eyebrow="A CLEARER VIEW OF YOUR SEARCH" title="Insights" description="A small snapshot of the effort you’ve put in so far." action={<button className="export-button" onClick={exportCsv}>↓ &nbsp;Export CSV</button>}/><div className="insight-cards"><article className="insight-card"><span>APPLICATIONS TRACKED</span><strong>{counts.total}</strong><small>Across every status</small></article><article className="insight-card"><span>INTERVIEW RATE</span><strong>{counts.total?Math.round(counts.interviews/counts.total*100):0}<i>%</i></strong><small>{counts.interviews} interview{counts.interviews===1?"":"s"} in progress</small></article><article className="insight-card"><span>OFFER RATE</span><strong>{counts.total?Math.round(counts.offers/counts.total*100):0}<i>%</i></strong><small>{counts.offers} offer{counts.offers===1?"":"s"} received</small></article></div><section className="insights-panel"><div className="section-heading"><div><h2>Applications by status</h2><p>Your search, at a glance.</p></div></div>{filters.slice(1).map(s=>{const count=applications.filter(a=>a.status===s).length;const share=applications.length?count/applications.length*100:0;return <div className="bar-row" key={s}><span>{s}</span><div><i className={`bar-${s.toLowerCase()}`} style={{width:`${share}%`}}/></div><b>{count}</b></div>})}</section></>}
      {view === "Settings" && <Settings user={user} setUser={setUser} announce={announce}/>}
      <footer className="footer"><span>Made for the next chapter <span className="footer-heart">♥</span></span><span>Take a breath. You’re right where you need to be.</span></footer></div></section>
      {toast&&<div className="toast" role="status">✓ &nbsp;{toast}</div>}{confirmation&&<ConfirmationDialog confirmation={confirmation} cancel={()=>setConfirmation(null)} confirm={()=>confirmation.kind === "delete" ? confirmDelete(confirmation.application) : confirmLogout()}/>} {modal&&<ApplicationModal initial={editing||emptyForm()} editing={Boolean(editing)} busy={busy} error={error} close={()=>setModal(false)} submit={saveApplication}/>}</main>;
}

function Stat({title,value,hint,tone}:{title:string;value:number;hint:string;tone:string}) { return <article className="stat-card"><div className="stat-head"><span>{title}</span><span className={`stat-icon ${tone}`}>{tone==="lavender"?"▦":tone==="peach"?"◷":"✳"}</span></div><div className="stat-value">{value}</div><div className="stat-foot">{hint}</div></article>; }
function PageHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action:React.ReactNode}) { return <div className="welcome-row"><div><div className="eyebrow"><span className="live-dot"/> {eyebrow}</div><h1>{title}</h1><p className="subtitle">{description}</p></div>{action}</div>; }

function ConfirmationDialog({confirmation,cancel,confirm}:{confirmation:Confirmation;cancel:()=>void;confirm:()=>void|Promise<void>}) {
  const deleting = confirmation.kind === "delete";
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)cancel();}}><section className="modal confirmation-modal" role="dialog" aria-modal="true" aria-labelledby="confirmation-title"><div className="modal-head"><div><span className="eyebrow">{deleting?"REMOVE APPLICATION":"LEAVE WORKSPACE"}</span><h2 id="confirmation-title">{deleting?"Delete this application?":"Log out of Rolegrove?"}</h2></div><button type="button" className="close-button" onClick={cancel} aria-label="Close">×</button></div><p className="confirmation-copy">{deleting?`This will permanently remove the ${confirmation.application.role} application at ${confirmation.application.company}. This action cannot be undone.`:"You can sign back in anytime with your email and password."}</p><div className="modal-actions"><button type="button" className="cancel-button" onClick={cancel}>Cancel</button><button type="button" className={deleting?"danger-button":"primary-button"} onClick={confirm}>{deleting?"Delete application":"Log out"}</button></div></section></div>;
}

function ApplicationModal({initial,editing,busy,error,close,submit}:{initial:Partial<Application>;editing:boolean;busy:boolean;error:string;close:()=>void;submit:(event:FormEvent<HTMLFormElement>)=>void}) {
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><form className="modal application-modal" onSubmit={submit}><div className="modal-head"><div><span className="eyebrow">{editing?"KEEP IT UP TO DATE":"A NEW OPPORTUNITY"}</span><h2>{editing?"Edit application":"Add application"}</h2></div><button type="button" className="close-button" onClick={close} aria-label="Close">×</button></div><div className="form-grid"><label>Company name<input name="company" defaultValue={initial.company} placeholder="e.g. Acme Studio" maxLength={100} required autoFocus/></label><label>Role title<input name="role" defaultValue={initial.role} placeholder="e.g. Product Designer" maxLength={120} required/></label><label>Status<select name="status" defaultValue={initial.status||"Applied"}>{filters.slice(1).map(s=><option key={s}>{s}</option>)}</select></label><label>Date applied<input name="applied_on" type="date" defaultValue={initial.applied_on||new Date().toISOString().slice(0,10)} required/></label><label>Location<input name="location" defaultValue={initial.location} placeholder="Remote or city" maxLength={120}/></label><label>Salary range<input name="salary" defaultValue={initial.salary} placeholder="e.g. $100k–$130k" maxLength={80}/></label><label className="full-field">Job posting URL<input name="job_url" type="url" defaultValue={initial.job_url} placeholder="https://company.com/careers/role" maxLength={500}/></label><label>Next step date<input name="follow_up_date" type="date" defaultValue={initial.follow_up_date}/></label><label>Next step<input name="follow_up_note" defaultValue={initial.follow_up_note} placeholder="Interview, follow-up…" maxLength={250}/></label><label className="full-field">Notes<textarea name="notes" defaultValue={initial.notes} rows={3} placeholder="Recruiter details, interview notes, or anything to remember…" maxLength={5000}/></label></div>{error&&<div className="form-error" role="alert">{error}</div>}<div className="modal-actions"><button type="button" className="cancel-button" onClick={close}>Cancel</button><button className="primary-button" type="submit" disabled={busy}>{busy?"Saving…":editing?"Save changes":"Add application"}</button></div></form></div>;
}

function Settings({user,setUser,announce}:{user:User;setUser:(user:User)=>void;announce:(message:string)=>void}) {
  const [profileError,setProfileError]=useState("");const [passwordError,setPasswordError]=useState("");const [saved,setSaved]=useState("");
  async function updateProfile(event:FormEvent<HTMLFormElement>){event.preventDefault();setProfileError("");setSaved("");const body=Object.fromEntries(new FormData(event.currentTarget).entries());const r=await fetch("/api/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await r.json();if(!r.ok){setProfileError(result.error);return;}setUser(result.user);setSaved("Your profile was updated.");}
  async function changePassword(event:FormEvent<HTMLFormElement>){event.preventDefault();setPasswordError("");const body=Object.fromEntries(new FormData(event.currentTarget).entries());const r=await fetch("/api/profile/password",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await r.json();if(!r.ok){setPasswordError(result.error);return;}event.currentTarget.reset();announce("Password updated");}
  return <><PageHeading eyebrow="YOUR PERSONAL WORKSPACE" title="Settings" description="Manage your account and keep your workspace up to date." action={null}/><div className="settings-grid"><section className="settings-card"><div className="section-heading"><div><h2>Profile</h2><p>Your name and email for this account.</p></div></div><form className="settings-form" onSubmit={updateProfile}><label>Full name<input name="name" defaultValue={user.name} required minLength={2} maxLength={70}/></label><label>Email address<input name="email" type="email" defaultValue={user.email} required maxLength={254}/></label>{profileError&&<div className="form-error">{profileError}</div>}{saved&&<div className="form-success">{saved}</div>}<button className="primary-button">Save profile</button></form></section><section className="settings-card"><div className="section-heading"><div><h2>Change password</h2><p>Choose a password you don’t use elsewhere.</p></div></div><form className="settings-form" onSubmit={changePassword}><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required/></label><label>New password<input name="newPassword" type="password" autoComplete="new-password" minLength={8} maxLength={128} required/></label>{passwordError&&<div className="form-error">{passwordError}</div>}<button className="primary-button">Update password</button></form></section><section className="settings-card data-settings"><div className="section-heading"><div><h2>Your data</h2><p>Take a portable copy of your application tracker.</p></div></div><p className="settings-copy">Export includes application details, statuses, notes, and follow-up dates in a spreadsheet-friendly CSV file.</p><button className="export-button" onClick={()=>announce("Open the Applications page to export your data")}>CSV export is on the Applications page</button><small>Rolegrove stores your data in this account’s private workspace.</small></section></div></>;
}
